events {}

http {

    # Redirect HTTP → HTTPS
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    # HTTPS SERVER
    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/ssl/selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

        # Prometheus FIRST
        location /prometheus/ {
            proxy_pass http://prometheus:9090/;
        }

        # Grafana
        location /grafana/ {
            proxy_pass http://grafana:3000/;
        }

        # Flask LAST
        location / {
            proxy_pass http://app:5000;
        }
    }
}
